// Code generated by enum-generate.go DO NOT EDIT.

package syncclient

import "gogs.mikescher.com/BlackForestBytes/goext/langext"
import "gogs.mikescher.com/BlackForestBytes/goext/enums"

const ChecksumEnumGenerator = "774bdc3948d5d1d7896e177657a062c54996141bc9e4ec9192ecd6351bf4107d" // GoExtVersion: 0.0.475

// ================================ SessionVerification ================================
//
// File:       session.go
// StringEnum: true
// DescrEnum:  false
// DataEnum:   false
//

var __SessionVerificationValues = []SessionVerification{
	VerificationNone,
	VerificationTOTP2FA,
	VerificationMail2FA,
}

var __SessionVerificationVarnames = map[SessionVerification]string{
	VerificationNone:    "VerificationNone",
	VerificationTOTP2FA: "VerificationTOTP2FA",
	VerificationMail2FA: "VerificationMail2FA",
}

func (e SessionVerification) Valid() bool {
	return langext.InArray(e, __SessionVerificationValues)
}

func (e SessionVerification) Values() []SessionVerification {
	return __SessionVerificationValues
}

func (e SessionVerification) ValuesAny() []any {
	return langext.ArrCastToAny(__SessionVerificationValues)
}

func (e SessionVerification) ValuesMeta() []enums.EnumMetaValue {
	return SessionVerificationValuesMeta()
}

func (e SessionVerification) String() string {
	return string(e)
}

func (e SessionVerification) VarName() string {
	if d, ok := __SessionVerificationVarnames[e]; ok {
		return d
	}
	return ""
}

func (e SessionVerification) TypeName() string {
	return "SessionVerification"
}

func (e SessionVerification) PackageName() string {
	return "syncclient"
}

func (e SessionVerification) Meta() enums.EnumMetaValue {
	return enums.EnumMetaValue{VarName: e.VarName(), Value: e, Description: nil}
}

func ParseSessionVerification(vv string) (SessionVerification, bool) {
	for _, ev := range __SessionVerificationValues {
		if string(ev) == vv {
			return ev, true
		}
	}
	return "", false
}

func SessionVerificationValues() []SessionVerification {
	return __SessionVerificationValues
}

func SessionVerificationValuesMeta() []enums.EnumMetaValue {
	return []enums.EnumMetaValue{
		VerificationNone.Meta(),
		VerificationTOTP2FA.Meta(),
		VerificationMail2FA.Meta(),
	}
}

// ================================ ================= ================================

func AllPackageEnums() []enums.Enum {
	return []enums.Enum{
		VerificationNone, // SessionVerification
	}
}
