// Code generated by enum-generate.go DO NOT EDIT.

package syncclient

import "gogs.mikescher.com/BlackForestBytes/goext/langext"
import "gogs.mikescher.com/BlackForestBytes/goext/enums"

const ChecksumEnumGenerator = "e94a4260b27d9224dcaa7121d1597704ca3e07118044af133d8d22f8391124bf" // GoExtVersion: 0.0.285

// ================================ SessionVerification ================================
//
// File:       session.go
// StringEnum: true
// DescrEnum:  false
//

var __SessionVerificationValues = []SessionVerification{
	VerificationNone,
	VerificationTOTP2FA,
	VerificationMail2FA,
}

var __SessionVerificationVarnames = map[SessionVerification]string{
	VerificationNone:    "VerificationNone",
	VerificationTOTP2FA: "VerificationTOTP2FA",
	VerificationMail2FA: "VerificationMail2FA",
}

func (e SessionVerification) Valid() bool {
	return langext.InArray(e, __SessionVerificationValues)
}

func (e SessionVerification) Values() []SessionVerification {
	return __SessionVerificationValues
}

func (e SessionVerification) ValuesAny() []any {
	return langext.ArrCastToAny(__SessionVerificationValues)
}

func (e SessionVerification) ValuesMeta() []enums.EnumMetaValue {
	return SessionVerificationValuesMeta()
}

func (e SessionVerification) String() string {
	return string(e)
}

func (e SessionVerification) VarName() string {
	if d, ok := __SessionVerificationVarnames[e]; ok {
		return d
	}
	return ""
}

func (e SessionVerification) Meta() enums.EnumMetaValue {
	return enums.EnumMetaValue{VarName: e.VarName(), Value: e, Description: nil}
}

func ParseSessionVerification(vv string) (SessionVerification, bool) {
	for _, ev := range __SessionVerificationValues {
		if string(ev) == vv {
			return ev, true
		}
	}
	return "", false
}

func SessionVerificationValues() []SessionVerification {
	return __SessionVerificationValues
}

func SessionVerificationValuesMeta() []enums.EnumMetaValue {
	return []enums.EnumMetaValue{
		VerificationNone.Meta(),
		VerificationTOTP2FA.Meta(),
		VerificationMail2FA.Meta(),
	}
}
